### ISSUE TITLE
レビュー用イシュー

### ISSUE THREAD

**Issue by kazushiwaki** [kazushiwaki/losscook#40]
■Webアプリの概要
ロスクック - 家庭の食品ロス削減をサポートするアプリ

概要
ロスクックは、家庭で発生する食品ロスの一因である「過剰除去」の削減を目指すアプリです。通常捨てられがちな食材の部位（人参の皮やキャベツの芯など）を活用したレシピを投稿・閲覧でき、他ユーザーのアイデアを参考に調理することで、食材を無駄なく使う知識を深められます。また、管理栄養士や栄養士から、栄養や調理に関する信頼性のある情報も提供されます。

背景と目的
日本の家庭で発生する食品ロスは年間約236万トン、そのうち約33万トンが過剰除去に起因しています。この問題に対し、過剰除去に特化したアプリがなかったため、ロスクックを立ち上げました。

ターゲット
料理をするが、過剰除去を避ける調理方法がわからない人が対象です。知識を増やし、家庭での食品ロス削減に貢献できます。

差別化ポイント
過剰除去をテーマにしたレシピ投稿アプリは他にないため、独自性が際立ちます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：38時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

■MVPリリースまで
- [x] 環境設定
- [x] Herokuにデプロイ
- [x] アカウント登録機能
- [x] ログイン・ログアウト機能
- [x] レシピ投稿機能
- [x] レシピ保存機能
- [x] レシピへのコメント機能
- [x] SNSへの投稿機能
- [x] チュートリアル機能
- [x] 管理者機能
- [x] 投稿のお気に入り総数によるランキング機能

■MVP後
- [x] レシピ以外の投稿機能
- [x] 自動補完機能付きの検索機能
- [x] ユーザーフィードバック機能

■MVPレビュー依頼予定日
予定日：20xx年 12月 5日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
概ね良さそうです。
LGTMです！
